import { coilDcr, type CatalogPart, type CatalogSeries, type CatalogTier } from './catalog.ts';

/**
 * Catalog exchange format: product SERIES as a standalone JSON file, so any
 * brand can be added without touching code — export the current catalog as an
 * editable template, add series (brand, kind, range, gauges/esr/powerW),
 * import it back. Imported series live NEXT TO the built-in set.
 */

export const CATALOG_FORMAT = 'acoustic-design-studio-catalog';
/** v1: series basics · v2: (reserved) · v3: eSeries/series_type grid, tier,
 *  price model (basePrice/base_price + costFactor/cost_factor), dcrFactor ·
 *  v4: flat `components` array with EXACT SKUs (value, dcr/esr, price, tier,
 *  gauge) — real market data beats generated grids. Both snake_case and
 *  camelCase spellings are accepted — catalog updates get generated by
 *  external tools (Gemini writes snake_case).
 *  The version field is informational: external generators bump it per DATA
 *  revision, not per format (Sanders v6 file was v4-format). Structural
 *  validation below is the real gate, so any numeric version is accepted. */
export const CATALOG_VERSION = 4;

/** What a catalog file yields: generated-grid SERIES and/or exact PARTS
 *  (v4 flat SKU databases carry `components`). */
export interface CatalogImport {
  series: CatalogSeries[];
  parts: CatalogPart[];
}

export class CatalogFileError extends Error {}

export function serializeCatalog(
  series: readonly CatalogSeries[],
  components: readonly CatalogPart[] = [],
): string {
  return JSON.stringify(
    {
      format: CATALOG_FORMAT,
      version: CATALOG_VERSION,
      savedAt: new Date().toISOString(),
      note:
        'Edit or add series and import this file. kind: L (coil, henry) | C (cap, farad) | ' +
        'R (resistor, ohm). range = [min, max] in SI units. Coils: gauges (wire mm, DCR is ' +
        'estimated per gauge; dcrFactor scales it — ~0.35 for iron cores). Caps: esr (ohm). ' +
        'Resistors: powerW. Optional per series: eSeries/series_type (E12|E24 value grid), ' +
        'tier (budget|standard|premium), basePrice/base_price + costFactor/cost_factor ' +
        '(priceEur = base + factor·value). A series with a built-in id OVERRIDES the built-in.',
      series,
      ...(components.length > 0 ? { components } : {}),
    },
    null,
    1,
  );
}

export function deserializeCatalog(text: string): CatalogImport {
  let d: Record<string, unknown>;
  try {
    d = JSON.parse(text) as Record<string, unknown>;
  } catch (e) {
    // Surface WHERE it breaks: hand-edited and AI-generated files carry
    // typos (Sanders v4 file had a stray quote on one value).
    throw new CatalogFileError(
      `Not a JSON file (${e instanceof Error ? e.message : 'parse error'}).`,
    );
  }
  if (d['format'] !== CATALOG_FORMAT) {
    throw new CatalogFileError('Not an Acoustic Design Studio catalog file.');
  }
  if (typeof d['version'] !== 'number' || !(d['version'] >= 1)) {
    throw new CatalogFileError('Catalog file has no valid version number.');
  }
  const raw = d['series'];
  const rawParts = d['components'];
  const hasSeries = Array.isArray(raw) && raw.length > 0;
  const hasParts = Array.isArray(rawParts) && rawParts.length > 0;
  if (!hasSeries && !hasParts) {
    throw new CatalogFileError('Catalog file contains no series.');
  }
  const seen = new Set<string>();
  const out: CatalogSeries[] = [];
  for (const s of (hasSeries ? (raw as Array<Record<string, unknown>>) : [])) {
    const id = s['id'];
    const brand = s['brand'];
    const series = s['series'];
    const kind = s['kind'];
    const range = s['range'];
    if (
      typeof id !== 'string' || id === '' ||
      typeof brand !== 'string' || brand === '' ||
      typeof series !== 'string' || series === '' ||
      (kind !== 'L' && kind !== 'C' && kind !== 'R') ||
      !Array.isArray(range) || range.length !== 2 ||
      typeof range[0] !== 'number' || typeof range[1] !== 'number' ||
      !(range[0] > 0) || !(range[1] > range[0])
    ) {
      throw new CatalogFileError(`Malformed series entry${typeof id === 'string' ? ` "${id}"` : ''}.`);
    }
    if (seen.has(id)) throw new CatalogFileError(`Duplicate series id "${id}".`);
    seen.add(id);
    const gauges = s['gauges'];
    if (gauges !== undefined && (!Array.isArray(gauges) || gauges.some((g) => !(typeof g === 'number' && g > 0)))) {
      throw new CatalogFileError(`Series "${id}": gauges must be positive numbers (wire mm).`);
    }
    if (kind === 'L' && (gauges === undefined || (gauges as number[]).length === 0)) {
      throw new CatalogFileError(`Series "${id}": a coil series needs at least one wire gauge.`);
    }
    // v3 extras — both spellings accepted (external tools write snake_case).
    const eSeriesRaw = s['eSeries'] ?? s['series_type'];
    if (eSeriesRaw !== undefined && eSeriesRaw !== 'E12' && eSeriesRaw !== 'E24') {
      throw new CatalogFileError(`Series "${id}": eSeries/series_type must be E12 or E24.`);
    }
    const tier = s['tier'];
    if (tier !== undefined && tier !== 'budget' && tier !== 'standard' && tier !== 'premium') {
      throw new CatalogFileError(`Series "${id}": tier must be budget, standard or premium.`);
    }
    const basePrice = s['basePrice'] ?? s['base_price'];
    if (basePrice !== undefined && !(typeof basePrice === 'number' && basePrice >= 0)) {
      throw new CatalogFileError(`Series "${id}": basePrice must be a number ≥ 0.`);
    }
    const costFactor = s['costFactor'] ?? s['cost_factor'];
    if (costFactor !== undefined && !(typeof costFactor === 'number' && costFactor >= 0)) {
      throw new CatalogFileError(`Series "${id}": costFactor must be a number ≥ 0.`);
    }
    const dcrFactor = s['dcrFactor'];
    if (dcrFactor !== undefined && !(typeof dcrFactor === 'number' && dcrFactor > 0 && dcrFactor <= 2)) {
      throw new CatalogFileError(`Series "${id}": dcrFactor must be in (0, 2].`);
    }

    out.push({
      id,
      brand,
      series,
      kind,
      range: [range[0], range[1]],
      ...(gauges !== undefined ? { gauges: gauges as number[] } : {}),
      ...(typeof s['esr'] === 'number' && s['esr'] >= 0 ? { esr: s['esr'] } : {}),
      ...(typeof s['powerW'] === 'number' && s['powerW'] > 0 ? { powerW: s['powerW'] } : {}),
      ...(eSeriesRaw !== undefined ? { eSeries: eSeriesRaw as 'E12' | 'E24' } : {}),
      ...(tier !== undefined ? { tier: tier as CatalogTier } : {}),
      ...(basePrice !== undefined ? { basePrice: basePrice as number } : {}),
      ...(costFactor !== undefined ? { costFactor: costFactor as number } : {}),
      ...(dcrFactor !== undefined ? { dcrFactor: dcrFactor as number } : {}),
    });
  }

  // v4 flat components: exact SKUs.
  const parts: CatalogPart[] = [];
  const seenSku = new Set<string>();
  for (const c of (hasParts ? (rawParts as Array<Record<string, unknown>>) : [])) {
    const id = c['sku'] ?? c['id'];
    const brand = c['brand'];
    const series = c['series'];
    const kind = c['kind'];
    const value = c['value'];
    if (
      typeof id !== 'string' || id === '' ||
      typeof brand !== 'string' || brand === '' ||
      typeof series !== 'string' || series === '' ||
      (kind !== 'L' && kind !== 'C' && kind !== 'R') ||
      typeof value !== 'number' || !(value > 0)
    ) {
      throw new CatalogFileError(
        `Malformed component entry${typeof id === 'string' ? ` "${id}"` : ''}.`,
      );
    }
    if (seenSku.has(id)) throw new CatalogFileError(`Duplicate component sku "${id}".`);
    seenSku.add(id);
    const tier = c['tier'];
    if (tier !== undefined && tier !== 'budget' && tier !== 'standard' && tier !== 'premium') {
      throw new CatalogFileError(`Component "${id}": tier must be budget, standard or premium.`);
    }
    const gauge = c['gauge'] ?? c['wireMm'];
    const dcr = c['dcr'];
    const esr = c['esr'];
    const price = c['price'] ?? c['priceEur'];
    const powerW = c['powerW'];
    const num = (v: unknown): number | undefined =>
      typeof v === 'number' && Number.isFinite(v) && v >= 0 ? v : undefined;
    const seriesR =
      kind === 'L'
        ? (num(dcr) ?? coilDcr(value, (num(gauge) ?? 1.4) || 1.4))
        : kind === 'C'
          ? (num(esr) ?? 0.02)
          : 0;
    parts.push({
      id,
      brand,
      series,
      kind,
      value,
      seriesR: Number(seriesR.toPrecision(3)),
      ...(num(gauge) !== undefined ? { wireMm: num(gauge) } : {}),
      ...(num(powerW) !== undefined && num(powerW)! > 0 ? { powerW: num(powerW) } : {}),
      ...(num(price) !== undefined ? { priceEur: num(price) } : {}),
      ...(tier !== undefined ? { tier: tier as CatalogTier } : {}),
    });
  }

  return { series: out, parts };
}
