/**
 * CASUS 1 AS A v2 RUN — one definition, shared by the generator script and the
 * acceptance test.
 *
 * `casus1.fixture.ts` turns the files on disk into an engine-v2 REPORT input.
 * This turns the same files into a CHAIN input, which is a different shape and
 * a different set of decisions: a grid, a judged band, the tuner settings, and
 * the silent-ghost banding a three-way union grid needs.
 *
 * It lives beside the engine and not inside either consumer for the reason
 * `casus1.fixture.ts` gives for itself: two copies of a fixture are two chances
 * for them to disagree about what casus 1 is. Here that would be worse than
 * usual — the generator writes netlists to disk and the test asserts a live run
 * reproduces them, so a drift between the two would look like a regression in
 * the engine.
 *
 * IT READS FROM DISK, so it is only ever imported from tests and from
 * `scripts/`. `browserSafe.test.ts` knows `*.fixture.ts` as an exception and
 * `toggleRegression.test.ts` pins that nothing in the bundle imports one.
 *
 * EVERY PARAMETER IS STATED HERE AND RECORDED IN `casus1_v2_herkomst.json`.
 * V15's process rule, applied to a run instead of to a metric: a result that
 * depends on a band, a grid or a set of tuner settings records them, or it is
 * not reproducible and therefore not a reference.
 */

import { logspace, resample, resampleImpedance, type GriddedResponse } from '../dsp.ts';
import type { Complex } from '../complex.ts';
import { runIngest } from './ingest/derive.ts';
import type { Manifest } from './ingest/manifest.ts';
import type { MeasurementFile } from './ingest/derive.ts';
import type { EngineV2Report } from './report.ts';
import { buildCandidateField, type CandidateFieldResult } from './predesign/candidateField.ts';
import { declareCandidateChoices } from './optimizer/candidateDeclaration.ts';
import type { GeneratedCandidate } from './predesign/candidates.ts';
import { AUTO_STRUCTS } from '../threeWayDesign.ts';
import { casus1AmpMinLoadOhm, loadGolden, type GoldenRefs } from './casus1.fixture.ts';

/**
 * How a branch reads OUTSIDE its own measured extent on a union grid.
 *
 * The app's own convention for a three-way: a branch that was not measured
 * there contributes silence rather than an extrapolation, so the sum carries
 * only real contributions. The number is the app's (`designSolve`), restated
 * here rather than imported so this fixture does not reach into a test.
 */
export const SILENT_GHOST_DB = -400;

/**
 * The analysis grid the chain runs on.
 *
 * A RESOLUTION choice, not a band — the same reasoning `ANALYSIS_GRID_POINTS`
 * carries. The ends are the app's own: 200 Hz is where the far-field span
 * begins on this measurement set (see the note on the chain-grid floor in
 * casebook V27) and 20 kHz is the top of the audio band. 96 points is the
 * precedent `f4b2_v2_worker_baseline.json` set, and it is stated so a baseline
 * made on 96 can never be compared against a run on 200.
 */
export const CASUS1_V2_GRID: number[] = logspace(200, 20000, 96);

/**
 * The band the SPL window and the RMS deviation are judged on.
 *
 * The lowest way's validity floor to the highest way's validity ceiling — what
 * "this system is valid over" means when the ways are measured separately.
 * Clipped to the grid, because a band wider than the data is not a band.
 */
export const CASUS1_V2_BAND_HZ: [number, number] = [397, 19500];

/** The run seed. Stated rather than defaulted, and recorded (A5e.4, P4 amendment). */
export const CASUS1_V2_SEED = 20260827;

/**
 * The tuner settings the run was made with — the APP'S OWN DEFAULTS, not a
 * minimal set.
 *
 * THE FIRST VERSION OF THIS BLOCK WAS MINIMAL AND IT WAS WRONG, and the mistake
 * is worth keeping written down because it is the whole reason a comparison
 * table exists. It left out `targets` (the staged pass's goal), `safety` (the
 * full-band ban on degeneration) and the audit thresholds, on the reasoning
 * that "every extra armed mechanism is a second thing that could explain a
 * difference between two runs". That reasoning is right for a REGRESSION and
 * exactly backwards for a PROPOSAL: those three are protections, and a tuner
 * without them delivers networks that are flat on the judged band and
 * degenerate outside it. Measured, on the first pass: min |Z| of 0.00 Ω — a
 * dead short — with the chain reporting a perfectly ordinary 1.90 dB of ripple,
 * because the ripple was measured where the network still worked.
 *
 * V26 row 31 says it in one line: `safety` is the "volle-band-verbod op
 * degeneratie". A candidate generated by A5d and tuned without it is not a
 * proposal about where the handover belongs; it is a proposal plus an
 * unprotected search, and comparing THAT against three designs made with the
 * protections on would have compared the wrong two things.
 *
 * So: the same values the app puts in `settings` on an ordinary three-way run,
 * with the app's own defaults where the designer states nothing.
 *
 * `ampMinLoadOhm` USED TO BE ABSENT HERE, and its absence was correct while the
 * project stated nothing: P4, and the F0 doctrine that an empty field is not a
 * judgement. It is stated now (`manifest_en_geometrie.gestelde_eisen`), so it
 * appears — READ from there rather than written here, because a project number
 * that exists in two places is a project number that will one day differ
 * between them. It goes in beside the rest for the same reason the app puts it
 * in both places: `settings.ampMinLoadOhm` is what the repair pass works
 * against, and `v2.gates.ampMinLoadOhm` (set by the caller, not here) is what
 * judges the delivered network. A floor that only judges arrives too late.
 */
export const CASUS1_AMP_MIN_LOAD_OHM: number | null = casus1AmpMinLoadOhm();

export const CASUS1_V2_SETTINGS = {
  phasePriority: 0.5,
  /* 'acoustic', which is the app's own default — and the second thing the first
   * pass got wrong. On 'filter' the same chain, started from the baseline's own
   * crossings, delivered 31.4 dB of ripple against 5.2 dB on 'acoustic', drifted
   * the handovers from 360/2250 to 856/3848 and left a 0.00 Ω load. A fixture
   * that does not run the app's own synthesis is not measuring the app. */
  synthMode: 'acoustic' as const,
  band: CASUS1_V2_BAND_HZ,
  /** The staged pass's goal — the app's `targetRipple` / `targetPhase` defaults. */
  targets: { rippleDb: 2.5, phaseDeg: 15 },
  breakupGuard: true,
  ampTarget: 'onAxis' as const,
  phaseMetric: 'band' as const,
  powerMetric: 'smooth' as const,
  catalogSnap: false,
  dissipationWeight: 0.05,
  powerFoldWeight: 0.5,
  costWeight: 0.0015,
  directivityWeight: 0,
  /** The app's own defaults for the source-resistance tiers. */
  rSourceDisqualifyOhm: 2.0,
  audit: { thresholds: { rSourceOhm: 1.0 } },
  /* Spread rather than assigned, so an unstated floor leaves the KEY absent
   * instead of present-and-undefined. `declareCandidateChoices` distinguishes
   * those two: undefined becomes an ABSENT declaration with the P4 reason, and
   * a missing key is the silent inheritance F4d ended. */
  ...(CASUS1_AMP_MIN_LOAD_OHM !== null ? { ampMinLoadOhm: CASUS1_AMP_MIN_LOAD_OHM } : {}),
};

/**
 * Points on the FULL-BAND safety grid.
 *
 * A resolution choice, and the same one the app makes (`logspace(lo, hi, 240)`
 * in `runVfOptimize`). The safety set exists to watch what the network does
 * OUTSIDE the judged band, so it gets its own grid over the drivers' whole
 * measured extent rather than the analysis grid. @p6-style rationale: a count,
 * not a frequency.
 */
const SAFETY_GRID_POINTS = 240;

/**
 * The candidate field for casus 1.
 *
 * The designer's stated order is 4 on both handovers — the same order the
 * casebook's own window references carry (`kruisvensters.*_orde4`) and the same
 * one every other casus-1 test states. Stating it keeps the field to positions
 * only; with 'auto' the derivation abstains and every buildable order becomes
 * its own candidate, which is correct and is 63 chains.
 */
export function casus1Field(report: EngineV2Report): CandidateFieldResult {
  return buildCandidateField({
    windowInputs: report.predesign.windowInputs,
    perPair: report.predesign.windowInputs.map(() => ({ statedOrder: 4 })),
    alignments: AUTO_STRUCTS,
  });
}

/**
 * The declaration that travels beside one casus-1 candidate.
 *
 * It states every protection the run arms, which is the point: `safety`,
 * `audit`, `staged` and `rSourceDisqualifyOhm` are CHOICE keys (V26 rows 31,
 * 33, 14 and 2), so on the v2 route they may only reach the tuner through the
 * candidate. The first version of this fixture proved why by leaving three of
 * them out — see the note on `CASUS1_V2_SETTINGS`.
 */
export function casus1V2Declaration(
  c: GeneratedCandidate,
  safety?: {
    freqs: number[];
    w: GriddedResponse;
    m: GriddedResponse;
    t: GriddedResponse;
    z: Record<string, Complex[]>;
  },
) {
  return {
    declaration: declareCandidateChoices({
      cages: c.crossings.map((x) => x.cageHz),
      windowFloorsHz: c.crossings.map((x) => x.windowHz[0]),
      multiWay: true,
      stated: {
        band: CASUS1_V2_BAND_HZ,
        staged: CASUS1_V2_SETTINGS.targets,
        ampTarget: CASUS1_V2_SETTINGS.ampTarget,
        powerMetric: CASUS1_V2_SETTINGS.powerMetric,
        phaseMetric: CASUS1_V2_SETTINGS.phaseMetric,
        catalogSnap: CASUS1_V2_SETTINGS.catalogSnap,
        breakupGuard: CASUS1_V2_SETTINGS.breakupGuard,
        rSourceDisqualifyOhm: CASUS1_V2_SETTINGS.rSourceDisqualifyOhm,
        audit: CASUS1_V2_SETTINGS.audit,
        ...(CASUS1_AMP_MIN_LOAD_OHM !== null
          ? { ampMinLoadOhm: CASUS1_AMP_MIN_LOAD_OHM }
          : {}),
        ...(safety ? { safety } : {}),
        zFloorStrict: true,
      },
    }),
    provenance: c.provenance,
    orderByModel: { mid: c.crossings[0].order, tweeter: c.crossings[1].order },
  };
}

/** Band a response to its own measured extent — silence outside it. */
function banded(
  grid: readonly number[],
  src: { grid: readonly number[]; db: readonly number[]; phaseDeg: readonly number[] },
): GriddedResponse {
  const g = resample(src.grid, src.db, src.phaseDeg, grid, { clampEdges: true });
  const f0 = src.grid[0];
  const f1 = src.grid[src.grid.length - 1];
  return {
    freq: [...grid],
    spl: g.spl.map((v, i) => (grid[i] < f0 || grid[i] > f1 ? SILENT_GHOST_DB : v)),
    phaseDeg: g.phaseDeg.map((v, i) => (grid[i] < f0 || grid[i] > f1 ? 0 : v)),
  };
}

/**
 * The three branch responses and the three impedances, on the chain grid.
 *
 * The responses are the ingest pass's UNCLIPPED complex sums (`onAxisFull`),
 * for the reason V13 established: the woofer is one way measured as two files,
 * and the pressure that matters is their complex sum. Unclipped because where
 * two branches CROSS is a property of the design rather than a measurement
 * claim — the clipped band belongs to the scans, not to the chain.
 */
export function casus1ChainInput(
  manifest: Manifest,
  files: readonly MeasurementFile[],
  golden: GoldenRefs = loadGolden(),
): {
  grid: readonly number[];
  w: GriddedResponse;
  m: GriddedResponse;
  t: GriddedResponse;
  driverZ: Record<string, Complex[]>;
  safety: {
    freqs: number[];
    w: GriddedResponse;
    m: GriddedResponse;
    t: GriddedResponse;
    z: Record<string, Complex[]>;
  };
} {
  void golden;
  const ingest = runIngest(manifest, files);
  const grid = CASUS1_V2_GRID;
  const curve = (driver: string): GriddedResponse => {
    const d = ingest.drivers.find((x) => x.driver === driver);
    const full = d?.onAxisFull;
    if (!full) throw new Error(`casus 1 has no on-axis sum for ${driver}`);
    return banded(grid, { grid: full.grid, db: full.db, phaseDeg: full.phaseDeg });
  };
  const driverZ: Record<string, Complex[]> = {};
  for (const e of manifest.entries) {
    if (e.kind !== 'Z') continue;
    const f = files.find((x) => x.entry.file === e.file);
    if (!f?.impedance) continue;
    driverZ[e.driver] = resampleImpedance(
      f.impedance.freq,
      f.impedance.magnitude,
      f.impedance.phaseDeg,
      grid,
    ).z;
  }
  /* THE SAFETY SET (V26 row 31): the same three branches and the same
   * impedances over the drivers' WHOLE measured extent, on their own grid. The
   * tuner watches it for degeneration outside the judged band — which is
   * precisely where an unprotected search hides its damage. Built here so the
   * script and the acceptance test cannot arm different protections. */
  const extents = ['woofer', 'mid', 'tweeter'].map((d) => {
    const full = ingest.drivers.find((x) => x.driver === d)?.onAxisFull;
    if (!full) throw new Error(`casus 1 has no on-axis sum for ${d}`);
    return [full.grid[0], full.grid[full.grid.length - 1]] as [number, number];
  });
  const sLo = Math.min(...extents.map((e) => e[0]));
  const sHi = Math.max(...extents.map((e) => e[1]));
  const sGrid = logspace(sLo, sHi, SAFETY_GRID_POINTS);
  const sCurve = (driver: string): GriddedResponse => {
    const full = ingest.drivers.find((x) => x.driver === driver)!.onAxisFull!;
    return banded(sGrid, { grid: full.grid, db: full.db, phaseDeg: full.phaseDeg });
  };
  const sZ: Record<string, Complex[]> = {};
  for (const e of manifest.entries) {
    if (e.kind !== 'Z') continue;
    const f = files.find((x) => x.entry.file === e.file);
    if (!f?.impedance) continue;
    sZ[e.driver] = resampleImpedance(
      f.impedance.freq,
      f.impedance.magnitude,
      f.impedance.phaseDeg,
      sGrid,
    ).z;
  }
  const safety = {
    freqs: sGrid,
    w: sCurve('woofer'),
    m: sCurve('mid'),
    t: sCurve('tweeter'),
    z: sZ,
  };
  return { grid, w: curve('woofer'), m: curve('mid'), t: curve('tweeter'), driverZ, safety };
}
