/**
 * CASUS 1 AS A v2 RUN — one definition, shared by the generator script and the
 * acceptance test.
 *
 * `casus1.fixture.ts` turns the files on disk into an engine-v2 REPORT input.
 * This turns the same files into a CHAIN input, which is a different shape and
 * a different set of decisions: a grid, a judged band, the tuner settings, and
 * the silent-ghost banding a three-way union grid needs.
 *
 * It lives beside the engine and not inside either consumer for the reason
 * `casus1.fixture.ts` gives for itself: two copies of a fixture are two chances
 * for them to disagree about what casus 1 is. Here that would be worse than
 * usual — the generator writes netlists to disk and the test asserts a live run
 * reproduces them, so a drift between the two would look like a regression in
 * the engine.
 *
 * IT READS FROM DISK, so it is only ever imported from tests and from
 * `scripts/`. `browserSafe.test.ts` knows `*.fixture.ts` as an exception and
 * `toggleRegression.test.ts` pins that nothing in the bundle imports one.
 *
 * EVERY PARAMETER IS STATED HERE AND RECORDED IN `casus1_v2_herkomst.json`.
 * V15's process rule, applied to a run instead of to a metric: a result that
 * depends on a band, a grid or a set of tuner settings records them, or it is
 * not reproducible and therefore not a reference.
 */

import { logspace, resample, resampleImpedance, type GriddedResponse } from '../dsp.ts';
import type { Complex } from '../complex.ts';
import { runIngest } from './ingest/derive.ts';
import type { Manifest } from './ingest/manifest.ts';
import type { MeasurementFile } from './ingest/derive.ts';
import type { EngineV2Report } from './report.ts';
import { buildCandidateField, type CandidateFieldResult } from './predesign/candidateField.ts';
import {
  declareCandidateChainChoices,
  declareCandidateChoices,
} from './optimizer/candidateDeclaration.ts';
import type { GeneratedCandidate } from './predesign/candidates.ts';
import { AUTO_STRUCTS } from '../threeWayDesign.ts';
import {
  casus1AmpMinLoadOhm,
  casus1LfResonantBudgetDb,
  loadGolden,
  type GoldenRefs,
} from './casus1.fixture.ts';
import {
  factsForWorker,
  type MeasurementFactsPayload,
} from './optimizer/measurementFacts.ts';

/**
 * How a branch reads OUTSIDE its own measured extent on a union grid.
 *
 * The app's own convention for a three-way: a branch that was not measured
 * there contributes silence rather than an extrapolation, so the sum carries
 * only real contributions. The number is the app's (`designSolve`), restated
 * here rather than imported so this fixture does not reach into a test.
 */
export const SILENT_GHOST_DB = -400;

/**
 * The analysis grid the chain runs on.
 *
 * A RESOLUTION choice, not a band — the same reasoning `ANALYSIS_GRID_POINTS`
 * carries. The ends are the app's own: 200 Hz is where the far-field span
 * begins on this measurement set (see the note on the chain-grid floor in
 * casebook V27) and 20 kHz is the top of the audio band. 96 points is the
 * precedent `f4b2_v2_worker_baseline.json` set, and it is stated so a baseline
 * made on 96 can never be compared against a run on 200.
 */
export const CASUS1_V2_GRID: number[] = logspace(200, 20000, 96);

/**
 * The band the SPL window and the RMS deviation are judged on.
 *
 * The lowest way's validity floor to the highest way's validity ceiling — what
 * "this system is valid over" means when the ways are measured separately.
 * Clipped to the grid, because a band wider than the data is not a band.
 */
export const CASUS1_V2_BAND_HZ: [number, number] = [397, 19500];

/** The run seed. Stated rather than defaulted, and recorded (A5e.4, P4 amendment). */
export const CASUS1_V2_SEED = 20260827;

/**
 * The tuner settings the run was made with — the APP'S OWN DEFAULTS, not a
 * minimal set.
 *
 * THE FIRST VERSION OF THIS BLOCK WAS MINIMAL AND IT WAS WRONG, and the mistake
 * is worth keeping written down because it is the whole reason a comparison
 * table exists. It left out `targets` (the staged pass's goal), `safety` (the
 * full-band ban on degeneration) and the audit thresholds, on the reasoning
 * that "every extra armed mechanism is a second thing that could explain a
 * difference between two runs". That reasoning is right for a REGRESSION and
 * exactly backwards for a PROPOSAL: those three are protections, and a tuner
 * without them delivers networks that are flat on the judged band and
 * degenerate outside it. Measured, on the first pass: min |Z| of 0.00 Ω — a
 * dead short — with the chain reporting a perfectly ordinary 1.90 dB of ripple,
 * because the ripple was measured where the network still worked.
 *
 * V26 row 31 says it in one line: `safety` is the "volle-band-verbod op
 * degeneratie". A candidate generated by A5d and tuned without it is not a
 * proposal about where the handover belongs; it is a proposal plus an
 * unprotected search, and comparing THAT against three designs made with the
 * protections on would have compared the wrong two things.
 *
 * So: the same values the app puts in `settings` on an ordinary three-way run,
 * with the app's own defaults where the designer states nothing.
 *
 * `ampMinLoadOhm` USED TO BE ABSENT HERE, and its absence was correct while the
 * project stated nothing: P4, and the F0 doctrine that an empty field is not a
 * judgement. It is stated now (`manifest_en_geometrie.gestelde_eisen`), so it
 * appears — READ from there rather than written here, because a project number
 * that exists in two places is a project number that will one day differ
 * between them. It goes in beside the rest for the same reason the app puts it
 * in both places: `settings.ampMinLoadOhm` is what the repair pass works
 * against, and `v2.gates.ampMinLoadOhm` (set by the caller, not here) is what
 * judges the delivered network. A floor that only judges arrives too late.
 */
export const CASUS1_AMP_MIN_LOAD_OHM: number | null = casus1AmpMinLoadOhm();

/**
 * V42/V43 — the stated LF budget, read from the manifest for the same reason
 * the floor above is: it is a project number and it has one home.
 *
 * IT DOES NOT BELONG IN `CASUS1_V2_SETTINGS`, and that is the difference from
 * the floor. `ampMinLoadOhm` goes to two places at once because it arms two
 * mechanisms — the chain's repair pass and the run's verdict. A lift budget
 * arms neither: it is an input to `invertBudgets`, which lives on the v2 side
 * only, so it travels in `v2.budgets.lfBumpBudgetDb` and nowhere else. A copy
 * in the chain settings would be a number with no reader.
 *
 * SINCE V43 IT IS ON THE RESONANT HALF of M-D's lift, and 1.4 dB rather than
 * V42's 2.5 — the manifest field is `lf_opslingering_budget_dB` and carries the
 * derivation. The transport key kept its name on purpose; see the fixture
 * helper and the manifest's `..._invoerpunt`.
 */
export const CASUS1_LF_RESONANT_BUDGET_DB: number | null = casus1LfResonantBudgetDb();

/**
 * V42 — THE ARMED GATES AND BUDGETS OF A CASUS-1 v2 RUN, in one place.
 *
 * WHY THIS EXISTS, and it is not tidiness. The generator and the acceptance
 * test each built this block themselves, and the moment V42 armed a budget in
 * the generator the test stopped reproducing the run it asserts about: it
 * re-ran a candidate the record says was REFUSED, without the budget that
 * refused it, got a network back, and failed. That is the same failure V27
 * wrote down — a run fixture that differs from the route it claims to measure —
 * and the fix is the one this file already applies to everything else: one
 * definition, two consumers.
 *
 * Spread at the use site (`gates: { ...CASUS1_V2_GATES }`) so an unstated
 * requirement arms nothing at all, which is what P4 asks for and what a casus
 * without these numbers still looks like.
 */
export const CASUS1_V2_GATES: { ampMinLoadOhm?: number } =
  CASUS1_AMP_MIN_LOAD_OHM !== null ? { ampMinLoadOhm: CASUS1_AMP_MIN_LOAD_OHM } : {};

export const CASUS1_V2_BUDGETS: { lfBumpBudgetDb?: number } =
  CASUS1_LF_RESONANT_BUDGET_DB !== null ? { lfBumpBudgetDb: CASUS1_LF_RESONANT_BUDGET_DB } : {};

export const CASUS1_V2_SETTINGS = {
  phasePriority: 0.5,
  /* 'acoustic', which is the app's own default — and the second thing the first
   * pass got wrong. On 'filter' the same chain, started from the baseline's own
   * crossings, delivered 31.4 dB of ripple against 5.2 dB on 'acoustic', drifted
   * the handovers from 360/2250 to 856/3848 and left a 0.00 Ω load. A fixture
   * that does not run the app's own synthesis is not measuring the app. */
  synthMode: 'acoustic' as const,
  band: CASUS1_V2_BAND_HZ,
  /** The staged pass's goal — the app's `targetRipple` / `targetPhase` defaults. */
  targets: { rippleDb: 2.5, phaseDeg: 15 },
  breakupGuard: true,
  ampTarget: 'onAxis' as const,
  phaseMetric: 'band' as const,
  powerMetric: 'smooth' as const,
  catalogSnap: false,
  dissipationWeight: 0.05,
  powerFoldWeight: 0.5,
  costWeight: 0.0015,
  directivityWeight: 0,
  /**
   * THE SOURCE-RESISTANCE TIERS: NEITHER IS STATED, AND THAT IS THE STATEMENT
   * (V34, P4).
   *
   * This block used to read `rSourceDisqualifyOhm: 2.0` and
   * `audit.thresholds.rSourceOhm: 1.0`, with the comment "the app's own
   * defaults for the source-resistance tiers". Every other project number in
   * this fixture is READ from `manifest_en_geometrie.gestelde_eisen` — the amp
   * floor is, and the note above `CASUS1_AMP_MIN_LOAD_OHM` says why — and these
   * two were not, because there was nothing to read: casus 1 states no
   * source-resistance requirement. What stood here was a UI default typed into
   * a fixture, which is exactly the pattern F0 removed for `ampMinLoadOhm`.
   *
   * WHY IT MATTERED, MEASURED. Until V34 the probe read the chain grid, where
   * it landed on the top of its own search window (640.2 Hz) rather than on the
   * woofer's resonance, and there every candidate scores well under 2 Ω. Read
   * where the quantity actually lives, the three v1 baselines score 3.98, 4.59
   * and 2.55 Ω — so an unasked-for 2.0 Ω limit would disqualify all three,
   * including the designer's own best filter. Repairing the probe without
   * withdrawing the default would have made the field worse than leaving both
   * alone; that is why V34 is one entry and not two.
   *
   * `rSourceDisqualifyOhm` is therefore simply ABSENT: `declareCandidateChoices`
   * files it with the P4 reason, and `withDeclaredSourceLimit` in the worker
   * makes the chain honour that instead of falling back to its own default.
   * The audit still RUNS — it is a protection, and V26 row 33 is why every
   * protection this app arms by default stays armed — but its source-resistance
   * tier is stated `null`: no limit, because nobody stated one. `null` and not
   * absent, because an absent `audit` would switch the whole part audit off.
   */
  audit: { thresholds: { rSourceOhm: null } },
  /**
   * V34 — the probe reads the full-band safety grid, not the chain grid.
   *
   * Stated here rather than left to the derivation for the same reason
   * `zFloorBarrierSource` is stated on the runs the comparison table is built
   * from: a before/after measurement has to be a run somebody can ask for. The
   * derivation in `declareCandidateChoices` would reach the same value on this
   * casus, and `choiceKeyGuard.test.ts` pins that it does.
   */
  rSourceProbeSource: 'safety' as const,
  /* Spread rather than assigned, so an unstated floor leaves the KEY absent
   * instead of present-and-undefined. `declareCandidateChoices` distinguishes
   * those two: undefined becomes an ABSENT declaration with the P4 reason, and
   * a missing key is the silent inheritance F4d ended. */
  ...(CASUS1_AMP_MIN_LOAD_OHM !== null ? { ampMinLoadOhm: CASUS1_AMP_MIN_LOAD_OHM } : {}),
};

/**
 * Points on the FULL-BAND safety grid.
 *
 * A resolution choice, and the same one the app makes (`logspace(lo, hi, 240)`
 * in `runVfOptimize`). The safety set exists to watch what the network does
 * OUTSIDE the judged band, so it gets its own grid over the drivers' whole
 * measured extent rather than the analysis grid. @p6-style rationale: a count,
 * not a frequency.
 */
const SAFETY_GRID_POINTS = 240;

/**
 * The candidate field for casus 1.
 *
 * The designer's stated order is 4 on both handovers — the same order the
 * casebook's own window references carry (`kruisvensters.*_orde4`) and the same
 * one every other casus-1 test states. Stating it keeps the field to positions
 * only; with 'auto' the derivation abstains and every buildable order becomes
 * its own candidate, which is correct and is 63 chains.
 */
export function casus1Field(report: EngineV2Report): CandidateFieldResult {
  return buildCandidateField({
    windowInputs: report.predesign.windowInputs,
    perPair: report.predesign.windowInputs.map(() => ({ statedOrder: 4 })),
    alignments: AUTO_STRUCTS,
  });
}

/**
 * The declaration that travels beside one casus-1 candidate.
 *
 * It states every protection the run arms, which is the point: `safety`,
 * `audit`, `staged` and `rSourceDisqualifyOhm` are CHOICE keys (V26 rows 31,
 * 33, 14 and 2), so on the v2 route they may only reach the tuner through the
 * candidate. The first version of this fixture proved why by leaving three of
 * them out — see the note on `CASUS1_V2_SETTINGS`.
 *
 * SINCE V34 ONE OF THEM IS STATED BY BEING ABSENT. `rSourceDisqualifyOhm` is
 * not listed below, and that is the declaration: casus 1 states no
 * source-resistance requirement, so the candidate carries none and nothing is
 * disqualified on it (P4). `rSourceProbeSource` takes its place — where the
 * probe reads is a choice this candidate does make.
 */
export function casus1V2Declaration(
  c: GeneratedCandidate,
  safety?: {
    freqs: number[];
    w: GriddedResponse;
    m: GriddedResponse;
    t: GriddedResponse;
    z: Record<string, Complex[]>;
  },
) {
  return {
    declaration: declareCandidateChoices({
      cages: c.crossings.map((x) => x.cageHz),
      windowFloorsHz: c.crossings.map((x) => x.windowHz[0]),
      multiWay: true,
      stated: {
        band: CASUS1_V2_BAND_HZ,
        staged: CASUS1_V2_SETTINGS.targets,
        ampTarget: CASUS1_V2_SETTINGS.ampTarget,
        powerMetric: CASUS1_V2_SETTINGS.powerMetric,
        phaseMetric: CASUS1_V2_SETTINGS.phaseMetric,
        catalogSnap: CASUS1_V2_SETTINGS.catalogSnap,
        breakupGuard: CASUS1_V2_SETTINGS.breakupGuard,
        audit: CASUS1_V2_SETTINGS.audit,
        rSourceProbeSource: CASUS1_V2_SETTINGS.rSourceProbeSource,
        ...(CASUS1_AMP_MIN_LOAD_OHM !== null
          ? { ampMinLoadOhm: CASUS1_AMP_MIN_LOAD_OHM }
          : {}),
        ...(safety ? { safety } : {}),
        zFloorStrict: true,
      },
    }),
    /* V41 — the two settings the DESIGN and SYNTHESIS steps read, which run
     * before the tuner exists. Nothing is stated here, so the derivation
     * applies: the app's own EQ budget and `synthesize`'s own lean threshold.
     * Stating them here instead would put two more app defaults in a fixture,
     * which is the pattern V34 removed for the source-resistance tiers. */
    chainDeclaration: declareCandidateChainChoices({ stated: {} }),
    provenance: c.provenance,
    orderByModel: { mid: c.crossings[0].order, tweeter: c.crossings[1].order },
  };
}

/**
 * V32 — THE MEASURED FACTS, ACROSS THE BORDER, THE WAY THE APP SENDS THEM.
 *
 * This fixture used to send NONE. That was invisible while every gate judged on
 * the chain's analysis grid: the worker fell back to its own R_e, to the whole
 * grid for validity, and to its own resonance classification, said so in the
 * notes, and nobody read the notes. V32 makes it load-bearing — with no
 * impedance sweep in the payload no electrical gate judges at all, so a fixture
 * that sends nothing would answer V32 by turning `M-B/|Z|` off, which is worse
 * than the leniency it replaces.
 *
 * So the whole payload crosses, through `factsForWorker` — the app's own bridge
 * (`App.tsx`, `v2Facts`) — and not a hand-picked half of it. Sending only the
 * sweep while withholding the validity interval that belongs to the same
 * measurement is exactly the incoherence F4b's leak 2 was about.
 *
 * `modelByDriverId` is the IDENTITY on this casus, and it is built rather than
 * written: the manifest names its drivers `woofer`/`mid`/`tweeter` and the
 * netlists use the same names as models. On a project where those two
 * vocabularies differ, `driverSlots.ts` is the bridge and this map is where it
 * would be used.
 */
export function casus1V2Facts(
  report: EngineV2Report,
  manifest: Manifest,
  files: readonly MeasurementFile[],
): MeasurementFactsPayload {
  const modelByDriverId: Record<string, string> = {};
  for (const d of report.ingest.drivers) modelByDriverId[d.driver] = d.driver;
  const sweepByDriverId: Record<
    string,
    { freq: readonly number[]; magnitude: readonly number[]; phaseDeg: readonly number[] }
  > = {};
  for (const e of manifest.entries) {
    if (e.kind !== 'Z') continue;
    const f = files.find((x) => x.entry.file === e.file);
    if (!f?.impedance) continue;
    sweepByDriverId[e.driver] = {
      freq: f.impedance.freq,
      magnitude: f.impedance.magnitude,
      phaseDeg: f.impedance.phaseDeg,
    };
  }
  return factsForWorker(report, modelByDriverId, sweepByDriverId);
}

/** Band a response to its own measured extent — silence outside it. */
function banded(
  grid: readonly number[],
  src: { grid: readonly number[]; db: readonly number[]; phaseDeg: readonly number[] },
): GriddedResponse {
  const g = resample(src.grid, src.db, src.phaseDeg, grid, { clampEdges: true });
  const f0 = src.grid[0];
  const f1 = src.grid[src.grid.length - 1];
  return {
    freq: [...grid],
    spl: g.spl.map((v, i) => (grid[i] < f0 || grid[i] > f1 ? SILENT_GHOST_DB : v)),
    phaseDeg: g.phaseDeg.map((v, i) => (grid[i] < f0 || grid[i] > f1 ? 0 : v)),
  };
}

/**
 * The three branch responses and the three impedances, on the chain grid.
 *
 * The responses are the ingest pass's UNCLIPPED complex sums (`onAxisFull`),
 * for the reason V13 established: the woofer is one way measured as two files,
 * and the pressure that matters is their complex sum. Unclipped because where
 * two branches CROSS is a property of the design rather than a measurement
 * claim — the clipped band belongs to the scans, not to the chain.
 */
export function casus1ChainInput(
  manifest: Manifest,
  files: readonly MeasurementFile[],
  golden: GoldenRefs = loadGolden(),
): {
  grid: readonly number[];
  w: GriddedResponse;
  m: GriddedResponse;
  t: GriddedResponse;
  driverZ: Record<string, Complex[]>;
  safety: {
    freqs: number[];
    w: GriddedResponse;
    m: GriddedResponse;
    t: GriddedResponse;
    z: Record<string, Complex[]>;
  };
} {
  void golden;
  const ingest = runIngest(manifest, files);
  const grid = CASUS1_V2_GRID;
  const curve = (driver: string): GriddedResponse => {
    const d = ingest.drivers.find((x) => x.driver === driver);
    const full = d?.onAxisFull;
    if (!full) throw new Error(`casus 1 has no on-axis sum for ${driver}`);
    return banded(grid, { grid: full.grid, db: full.db, phaseDeg: full.phaseDeg });
  };
  const driverZ: Record<string, Complex[]> = {};
  for (const e of manifest.entries) {
    if (e.kind !== 'Z') continue;
    const f = files.find((x) => x.entry.file === e.file);
    if (!f?.impedance) continue;
    driverZ[e.driver] = resampleImpedance(
      f.impedance.freq,
      f.impedance.magnitude,
      f.impedance.phaseDeg,
      grid,
    ).z;
  }
  /* THE SAFETY SET (V26 row 31): the same three branches and the same
   * impedances over the drivers' WHOLE measured extent, on their own grid. The
   * tuner watches it for degeneration outside the judged band — which is
   * precisely where an unprotected search hides its damage. Built here so the
   * script and the acceptance test cannot arm different protections. */
  const extents = ['woofer', 'mid', 'tweeter'].map((d) => {
    const full = ingest.drivers.find((x) => x.driver === d)?.onAxisFull;
    if (!full) throw new Error(`casus 1 has no on-axis sum for ${d}`);
    return [full.grid[0], full.grid[full.grid.length - 1]] as [number, number];
  });
  const sLo = Math.min(...extents.map((e) => e[0]));
  const sHi = Math.max(...extents.map((e) => e[1]));
  const sGrid = logspace(sLo, sHi, SAFETY_GRID_POINTS);
  const sCurve = (driver: string): GriddedResponse => {
    const full = ingest.drivers.find((x) => x.driver === driver)!.onAxisFull!;
    return banded(sGrid, { grid: full.grid, db: full.db, phaseDeg: full.phaseDeg });
  };
  const sZ: Record<string, Complex[]> = {};
  for (const e of manifest.entries) {
    if (e.kind !== 'Z') continue;
    const f = files.find((x) => x.entry.file === e.file);
    if (!f?.impedance) continue;
    sZ[e.driver] = resampleImpedance(
      f.impedance.freq,
      f.impedance.magnitude,
      f.impedance.phaseDeg,
      sGrid,
    ).z;
  }
  const safety = {
    freqs: sGrid,
    w: sCurve('woofer'),
    m: sCurve('mid'),
    t: sCurve('tweeter'),
    z: sZ,
  };
  return { grid, w: curve('woofer'), m: curve('mid'), t: curve('tweeter'), driverZ, safety };
}
